services:
  server-1:
    build: .
    image: rl-final:latest
    ports:
      - "5001:5000"
    volumes:
      - ./results:/workingdirectory/results

  server-2:
    image: rl-final:latest
    ports:
      - "5002:5000"
    volumes:
      - ./results:/workingdirectory/results

  server-3:
    image: rl-final:latest
    ports:
      - "5003:5000"
    volumes:
      - ./results:/workingdirectory/results

  server-4:
    image: rl-final:latest
    ports:
      - "5004:5000"
    volumes:
      - ./results:/workingdirectory/results

  server-5:
    image: rl-final:latest
    ports:
      - "5005:5000"
    volumes:
      - ./results:/workingdirectory/results

  server-6:
    image: rl-final:latest
    ports:
      - "5006:5000"
    volumes:
      - ./results:/workingdirectory/results

  server-7:
    image: rl-final:latest
    ports:
      - "5007:5000"
    volumes:
      - ./results:/workingdirectory/results

  server-8:
    image: rl-final:latest
    ports:
      - "5008:5000"
    volumes:
      - ./results:/workingdirectory/results